FROM debian:stretch-slim

#Install Prerequisite Software and clean up after
RUN apt-get -yqq update && \
    apt-get -yqq install ruby ruby-dev make gcc g++ nano less && \
    gem install jekyll -v 3.7.0 && \
    gem install bundler && \
    apt-get -yqq purge ruby-dev make gcc g++ *-dev && \
    rm -rf /var/lib/apt/lists/*

COPY ./addfiles/nanorc.txt /root/.nanorc
COPY ./addfiles/bashrc.txt /root/.bashrc
