FROM debian:stretch-slim

#Install Prerequisite Software and clean up after
RUN apt-get -yqq update && \
    apt-get -yqq install ruby ruby-dev make gcc g++ nano less git && \
    gem install jekyll && \
    gem install bundler && \
    apt-get -yqq purge ruby-dev make gcc g++ *-dev && \
    rm -rf /var/lib/apt/lists/*

ADD ./addfiles/nanorc.txt /root/.nanorc
ADD ./addfiles/bashrc.txt /root/.bashrc
